import {
  AbrasionIcon,
  AdhesivenessIcon,
  DuctilityIcon,
  AngularityIcon,
  PenetrationIcon,
  SandEquivalentIcon,
  GranulometryIcon,
  ShapeIndexIcon,
  SpecifyMassIcon,
  ElongatedParticlesIcon,
  SofteningPointIcon,
  FlashPointIcon,
  ElasticRecoveryIcon,
  RotationalIcon,
  RtcdIcon,
  FwdIcon,
  InducedMoistureDamageIcon,
  DurabilityIcon,
  CantabrianIcon,
  FatigueIcon,
  MarshallIconPng,
  StorageStabilityIcon,
  FlowNumberIcon,
  MSCRIcon,
  ResiliencyModuleIcon,
  RiceTestIcon,
} from '@/assets';
import { FilterOption } from '@/components/molecules/buttons/filter';
import { StandardsTemplate } from '@/components/templates/standards';
import { Standard } from '@/interfaces/common';
import { t } from 'i18next';
import { NextPage } from 'next';

const AsphaltStandards: NextPage = () => {
  const standards: Standard[] = [
    {
      //title: t('abrasion.los.angeles'),
      title: 'Abrasão Los Angeles -  DNIT 451/2024 – ME',
      icon: AbrasionIcon,
      key: 'abrasion',
      standard: 'DNER - ME 035/98',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_451_2024_me.pdf',
      type: 'aggregates',
    },
    {
      //title: t('adhesiveness'),
      title: 'Adesividade - DNIT 452/2024 – ME', 
      icon: AdhesivenessIcon,
      key: 'adhesiveness',
      standard: 'DNER - ME 078/94',
      //link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dner_me_078_94-1.pdf',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_452_2024_me.pdf',
      type: 'aggregates',
    },
    {
      //title: t('induced.moisture.damage'),
      title: 'Dano por Umidade Induzida -DNIT 180/2018 - ME',
      icon: InducedMoistureDamageIcon,
      key: 'inducedMoistureDamage',
      standard: 'DNIT 180/2018 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_180_2018_me-1.pdf',
      type: 'aggregates',
    },
    {
      //title: t('ductility'),
      title: 'Ductibilidade - DNIT ME 163/12',
      icon: DuctilityIcon,
      key: 'ductility',
      standard: 'DNER - ME 163/98',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dner_me_163_98.pdf',
      type: 'asphaltBinder',
    },
    {
      //Consertar link de durability
      //title: t('durability'),
      title: 'Durabilidade - DNIT 446/2024 – ME',
      icon: DurabilityIcon,
      key: 'durability',
      standard: 'DNER - ME 089/94',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_446_me_avaliacao-de-durabilidade-de-agregados_com-incorporacao-da-errata-1.pdf',
      type: 'aggregates',
    },
    {
      //title: t('cantabro.essay'),
      title: 'Ensaio Cântabro - DNIT 136/2018 - ME',
      icon: CantabrianIcon,
      key: 'cantabrian',
      standard: 'DNER - ME 383/99',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_136_2018_me-1.pdf',
      type: 'aggregates',
    },
    {
      //title: t('angularity.essay'),
      title: 'Angularidade - DNIT 415/2019 - ME',
      icon: AngularityIcon,
      key: 'angularity',
      standard: 'DNER - ME 415/2019',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit415_2019_me.pdf',
      type: 'aggregates',
    },
    {
      //title: t('fatigue.essay'),
      title: 'Ensaio de Fadiga - DNIT - ME 183/2018',
      icon: FatigueIcon,
      key: 'fatigue',
      standard: 'DNIT - ME 183/2018',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_183_2018_me-1.pdf',
      type: 'asphaltBinder',
    },
    {
      //title: t('penetration.essay'),
      title: 'Ensaio de Penetração -  DNIT - ME 155/2010',
      icon: PenetrationIcon,
      key: 'penetration',
      standard: 'DNIT - ME 155/2010',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_155_2010_me.pdf',
      type: 'asphaltBinder',
    },
    {
      //title: t('marshall.essay'),
      title: 'Ensaio Marshall - DNIT 447/2024 – ME',
      icon: MarshallIconPng,
      key: 'marshall',
      standard: 'DNER - ME 043/95',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_447_2024_me_estabilidade_marshall_com_incorporacao_errata_1.pdf',
      type: 'asphaltMix',
    },
    {
      //title: t('sand.equivalent'),
      title: 'Equivalente de Areia - DNIT 450/2024 – ME',
      icon: SandEquivalentIcon,
      key: 'sandEquivalent',
      standard: 'DNER - ME 054/97',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_450_2024_me-1.pdf',
      type: 'aggregates',
    },
    {
      //title: t('storage.stability'),
      title: 'Estabilidade à estocagem - DNIT 384/2022 – ME',
      icon: StorageStabilityIcon,
      key: 'storageStability',
      standard: 'DNER - ME 384/99',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_384_2022_me.pdf',
      type: 'asphaltBinder',
    },
    {
      //title: t('drop.weight.deflectometer'),
      title: 'Deflectômetro de queda de peso - DNIT 184/2018 - ME',
      icon: FwdIcon,
      key: 'fallingWeightDeflectometer',
      standard: 'DNER - PRO 273/96',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_184_2018_me-1.pdf',

      type: 'asphaltMix',
    },
    {
      //title: t('flow.number'),
      title: 'Número de fluxo - DNIT 184/2018',
      icon: FlowNumberIcon,
      key: 'flowNumber',
      standard: 'DNIT 184/2018',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_184_2018_me-1.pdf',
      type: 'asphaltMix',
    },
    {
      //title: t('multiple.stress.creep.recovery'),
      title: 'Fluência e Recuperação Sob Tensões Múltiplas (MSCR) - DNIT 423/2020 - ME',
      icon: MSCRIcon,
      key: 'mscr',
      standard: 'DNIT 423/2020 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_423_2020_me.pdf',
      type: 'asphaltMix',
    },
    {
      //title: t('sieving.granulometry'),
      title: 'Granulometria por Peneiramento - DNIT 163/2010 - ME',
      icon: GranulometryIcon,
      key: 'granulometry-asphalt',
      standard: 'DNER - ME 083/98',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dner-me083-98.pdf',
      type: 'aggregates',
    },
    {
      //title: t('shape.index'),
      title: 'Índice de Forma - DNIT 424/2020 - ME',
      icon: ShapeIndexIcon,
      key: 'shapeIndex',
      standard: 'DNIT 424/2020 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_424_2020_me.pdf',
      type: 'aggregates',
    },
    {
      //title: t('specific.mass-coarse.aggregate'),
      title: 'Massa Específica - Agregrado Graúdo - DNIT 413/2021 - ME',
      icon: SpecifyMassIcon,
      key: 'specifyMassBigAggregates',
      standard: 'DNIT 413/2021 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_413_2021_me.pdf',
      type: 'aggregates',
    },
    {
      //title: t('specific.mass-fine.aggregate'),
      title: 'Massa Específica - Agregado Miúdo - DNIT 411/2021 - ME',
      icon: SpecifyMassIcon,
      key: 'specifyMassSmallAggregates',
      standard: 'DNIT 411/2021 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_411_2021_me-1.pdf',
      type: 'aggregates',
    },
    {
      //title: t('resilience.module'),
      title: 'Módulo de Resiliência - DNIT 135/2018 - ME',
      icon: ResiliencyModuleIcon,
      key: 'resilienceModule',
      standard: 'DNIT 135/2018 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_135_2018_me-2.pdf',
      type: 'asphaltMix',
    },
    {
      //title: t('elongated.flattened.particles'),
      title: 'Partículas Alongadas e Achatadas - DNIT 429/2020 - ME',
      icon: ElongatedParticlesIcon,
      key: 'elongatedParticles',
      standard: 'DNIT 429/2020 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_429_2020_me-3.pdf',
      type: 'aggregates',
    },
    {
      //title: t('softening.point'),
      title: 'Ponto de Amolecimento - DNIT 131/2010 - ME',
      icon: SofteningPointIcon,
      key: 'softeningPoint',
      standard: 'DNIT 131/2010 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_131_2010_me.pdf',
      type: 'asphaltBinder',
    },
    {
      //title: t('flash.point'),
      title: 'Ponto de Fulgor - DNIT - ME 148/2010',
      icon: FlashPointIcon,
      key: 'flashPoint',
      standard: 'DNER - ME 148/94',
      //link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dner_me_148_94.pdf',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/especificacao-de-servico-es/dnit_148_2012_es.pdf',
      type: 'asphaltBinder',
    },
    {
      //title: t('elastic.recovery'),
      title: 'Recuperação Elástica -  DNIT 130/2010 - ME ',
      icon: ElasticRecoveryIcon,
      key: 'elasticRecovery',
      standard: 'DNER 130/2010 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_130_2010_me.pdf',
      type: 'asphaltBinder',
    },
    { 
      //title: t('tensile.strength.by.diametral.compression-rt'),
      title: 'Resistência à Tração por Compressão Diametral - RT - DNIT 136/2018 - ME',
      icon: RtcdIcon,
      key: 'rtcd',
      standard: 'DNIT 136/2018 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_136_2018_me-1.pdf',
      type: 'asphaltMix',
    },
    {
      //title: t('rice.method'),
      title: 'Método Rice - DNIT 136/2018 - ME',
      icon: RiceTestIcon,
      key: 'rice',
      standard: 'DNIT 136/2018 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_136_2018_me-1.pdf',
      type: 'asphaltMix',
    },
    {
      //title: t('rotational.viscosity'),
      title: 'Viscosidade Rotacional - DNIT 427/2020 - ME',
      icon: RotationalIcon,
      key: 'rotational',
      standard: 'DNIT 427/2020 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_427_2020_me-2.pdf',
      type: 'asphaltBinder',
    },
  ];

  const filterOptions: FilterOption[] = [
    { key: 'all', title: t('all'), isSelected: true },
    { key: 'aggregates', title: t('aggregates'), isSelected: false },
    { key: 'asphaltMix', title: t('asphalt.mixtures'), isSelected: false },
    { key: 'asphaltBinder', title: t('asphalt.binder'), isSelected: false },
  ];

  return <StandardsTemplate standards={standards} filterOptions={filterOptions} />;
};

export default AsphaltStandards;
