import {
  AbrasionIcon,
  AdhesivenessIcon,
  DuctilityIcon,
  AngularityIcon,
  PenetrationIcon,
  SandEquivalentIcon,
  GranulometryIcon,
  ShapeIndexIcon,
  SpecifyMassIcon,
  ElongatedParticlesIcon,
  SofteningPointIcon,
  FlashPointIcon,
  ElasticRecoveryIcon,
  RotationalIcon,
  RtcdIcon,
  FwdIcon,
  InducedMoistureDamageIcon,
  DurabilityIcon,
  CantabrianIcon,
  FatigueIcon,
  MarshallIconPng,
  StorageStabilityIcon,
  FlowNumberIcon,
  MSCRIcon,
  ResiliencyModuleIcon,
  RiceTestIcon,
} from '@/assets';
import { FilterOption } from '@/components/molecules/buttons/filter';
import { StandardsTemplate } from '@/components/templates/standards';
import { Standard } from '@/interfaces/common';
import { t } from 'i18next';
import { NextPage } from 'next';

const AsphaltStandards: NextPage = () => {
  const standards: Standard[] = [
    {
      title: t('asphalt.standards.abrasion-los-angeles'),
      icon: AbrasionIcon,
      key: 'abrasion',
      standard: 'DNIT - ME 035/98',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_451_2024_me.pdf',
      type: 'aggregates',
    },
    {
      title: t('asphalt.standards.adhesiveness'),
      icon: AdhesivenessIcon,
      key: 'adhesiveness',
      standard: 'DNIT - ME 078/94',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dner_me_078_94-1.pdf',
      type: 'aggregates',
    },
    {
      title: t('asphalt.standards.induced.moisture.damage'),
      icon: InducedMoistureDamageIcon,
      key: 'inducedMoistureDamage',
      standard: 'DNIT 180/2018 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_180_2018_me-1.pdf',
      type: 'aggregates',
    },
    {
      title: t('asphalt.standards.ductility'),
      icon: DuctilityIcon,
      key: 'ductility',
      standard: 'DNIT - ME 163/98',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dner_me_163_98.pdf',
      type: 'asphaltBinder',
    },
    {
      title: t('asphalt.standards.durability'),
      icon: DurabilityIcon,
      key: 'durability',
      standard: 'DNIT - ME 089/94',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_446_me_avaliacao-de-durabilidade-de-agregados_com-incorporacao-da-errata-1.pdf',
      type: 'aggregates',
    },
    {
      title: t('asphalt.standards.cantabro'),
      icon: CantabrianIcon,
      key: 'cantabrian',
      standard: 'DNIT - ME 383/99',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dner_me_383_99.pdf',
      type: 'aggregates',
    },
    {
      title: t('asphalt.standards.angularity'),
      icon: AngularityIcon,
      key: 'angularity',
      standard: 'DNIT - ME 415/2019',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit415_2019_me.pdf',
      type: 'aggregates',
    },
    {
      title: t('asphalt.standards.fatigue'),
      icon: FatigueIcon,
      key: 'fatigue',
      standard: 'DNIT - ME 183/2018',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_183_2018_me-1.pdf',
      type: 'asphaltBinder',
    },
    {
      title: t('asphalt.standards.penetration'),
      icon: PenetrationIcon,
      key: 'penetration',
      standard: 'DNIT - ME 155/2010',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_155_2010_me.pdf',
      type: 'asphaltBinder',
    },
    {
      title: t('asphalt.standards.marshall'),
      icon: MarshallIconPng,
      key: 'marshall',
      standard: 'DNIT - ME 043/95',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_447_2024_me.pdf',
      type: 'asphaltMix',
    },
    {
      title: t('asphalt.standards.sand-equivalent'),
      icon: SandEquivalentIcon,
      key: 'sandEquivalent',
      standard: 'DNIT - ME 054/97',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_450_2024_me-1.pdf',
      type: 'aggregates',
    },
    {
      title: t('asphalt.standards.storage-stability'),
      icon: StorageStabilityIcon,
      key: 'storageStability',
      standard: 'DNIT - ME 384/99',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dner_me_384_99.pdf',
      type: 'asphaltBinder',
    },
    {
      title: t('asphalt.standards.drop-weight-deflectometer'),
      icon: FwdIcon,
      key: 'fwd',
      standard: 'DNIT - PRO 273/96',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/procedimento-de-ensaio-pro/dnit-pro-273-96.pdf',
      type: 'asphaltMix',
    },
    {
      title: t('asphalt.standards.flow-number'),
      icon: FlowNumberIcon,
      key: 'flowNumber',
      standard: 'DNIT 184/2018 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_184_2018_me-1.pdf',
      type: 'asphaltMix',
    },
    {
      title: t('asphalt.standards.multiple-stress-creep-recovery'),
      icon: MSCRIcon,
      key: 'mscr',
      standard: 'DNIT 423/2020 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_423_2020_me.pdf',
      type: 'asphaltMix',
    },
    {
      title: t('asphalt.standards.sieving-granulometry'),
      icon: GranulometryIcon,
      key: 'granulometry',
      standard: 'DNIT - ME 083/98',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dner-me083-98.pdf',
      type: 'aggregates',
    },
    {
      title: t('asphalt.standards.shape-index'),
      icon: ShapeIndexIcon,
      key: 'shapeIndex',
      standard: 'DNIT 424/2020 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_424_2020_me.pdf',
      type: 'aggregates',
    },
    {
      title: t('asphalt.standards.coarse-specific-mass'),
      icon: SpecifyMassIcon,
      key: 'specifyMassBigAggregates',
      standard: 'DNIT 413/2021 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_413_2021_me.pdf',
      type: 'aggregates',
    },
    {
      title: t('asphalt.standards.fine-specific-mass'),
      icon: SpecifyMassIcon,
      key: 'specifyMassSmallAggregates',
      standard: 'DNIT 411/2021 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_411_2021_me-1.pdf',
      type: 'aggregates',
    },
    {
      title: t('asphalt.standards.resilience-module'),
      icon: ResiliencyModuleIcon,
      key: 'resilienceModule',
      standard: 'DNIT 135/2018 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_135_2018_me-2.pdf',
      type: 'asphaltMix',
    },
    {
      title: t('asphalt.standards.elongated.flattened.particles'),
      icon: ElongatedParticlesIcon,
      key: 'elongatedParticles',
      standard: 'DNIT 429/2020 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_429_2020_me-3.pdf',
      type: 'aggregates',
    },
    {
      title: t('asphalt.standards.softening.point'),
      icon: SofteningPointIcon,
      key: 'softeningPoint',
      standard: 'DNIT 131/2010 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_131_2010_me.pdf',
      type: 'asphaltBinder',
    },
    {
      title: t('asphalt.standards.flash-point'),
      icon: FlashPointIcon,
      key: 'flashPoint',
      standard: 'DNIT - ME 148/94',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dner_me_148_94.pdf',
      type: 'asphaltBinder',
    },
    {
      title: t('asphalt.standards.elastic-recovery'),
      icon: ElasticRecoveryIcon,
      key: 'elasticRecovery',
      standard: 'DNIT 130/2010 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_130_2010_me.pdf',
      type: 'asphaltBinder',
    },
    { 
      title: t('asphalt.standards.tensile.strength.by.diametral.compression'),
      icon: RtcdIcon,
      key: 'rtcd',
      standard: 'DNIT 136/2018 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_136_2018_me-1.pdf',
      type: 'asphaltMix',
    },
    {
      title: t('asphalt.standards.rice-method'),
      icon: RiceTestIcon,
      key: 'rice',
      standard: 'DNIT 179/2018 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_179_2018_me.pdf',
      type: 'asphaltMix',
    },
    {
      title: t('asphalt.standards.rotational-viscosity'),
      icon: RotationalIcon,
      key: 'rotational',
      standard: 'DNIT 427/2020 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_427_2020_me-2.pdf',
      type: 'asphaltBinder',
    },
  ];

  const filterOptions: FilterOption[] = [
    { key: 'all', title: t('all'), isSelected: true },
    { key: 'aggregates', title: t('aggregates'), isSelected: false },
    { key: 'asphaltMix', title: t('asphalt.mixtures'), isSelected: false },
    { key: 'asphaltBinder', title: t('asphalt.binder'), isSelected: false },
  ];

  return <StandardsTemplate standards={standards} filterOptions={filterOptions} />;
};

export default AsphaltStandards;
