import {
  AbrasionIcon,
  AdhesivenessIcon,
  DuctilityIcon,
  AngularityIcon,
  PenetrationIcon,
  SandEquivalentIcon,
  GranulometryIcon,
  ShapeIndexIcon,
  SpecifyMassIcon,
  ElongatedParticlesIcon,
  SofteningPointIcon,
  FlashPointIcon,
  ElasticRecoveryIcon,
  RotationalIcon,
  RtcdIcon,
  FwdIcon,
  InducedMoistureDamageIcon,
  DurabilityIcon,
  CantabrianIcon,
  FatigueIcon,
  MarshallIconPng,
  StorageStabilityIcon,
  FlowNumberIcon,
  MSCRIcon,
  ResiliencyModuleIcon,
  RiceTestIcon,
} from '@/assets';
import { FilterOption } from '@/components/molecules/buttons/filter';
import { StandardsTemplate } from '@/components/templates/standards';
import { Standard } from '@/interfaces/common';
import { t } from 'i18next';
import { NextPage } from 'next';

const AsphaltStandards: NextPage = () => {
  const standards: Standard[] = [
    {
      title: t('abrasion.los.angeles'),
      icon: AbrasionIcon,
      key: 'abrasion',
      standard: 'DNER - ME 035/98',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dner-me035-98.pdf',
      type: 'aggregates',
    },
    {
      title: t('adhesiveness'),
      icon: AdhesivenessIcon,
      key: 'adhesiveness',
      standard: 'DNER- ME 078/94',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dner_me_078_94-1.pdf',
      type: 'aggregates',
    },
    {
      title: t('induced.moisture.damage'),
      icon: InducedMoistureDamageIcon,
      key: 'inducedMoistureDamage',
      standard: 'DNIT 180/2018 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_180_2018_me-1.pdf',
      type: 'aggregates',
    },
    {
      title: t('ductility'),
      icon: DuctilityIcon,
      key: 'ductility',
      standard: 'DNER - ME 163/98',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dner_me_163_98.pdf',
      type: 'asphaltBinder',
    },
    {
      title: t('durability'),
      icon: DurabilityIcon,
      key: 'durability',
      standard: 'DNER - ME 089/94',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dner_me_089_94.pdf',
      type: 'aggregates',
    },
    {
      title: t('cantabro.essay'),
      icon: CantabrianIcon,
      key: 'cantabrian',
      standard: 'DNER - ME 383/99',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dner_me_383_99.pdf',
      type: 'aggregates',
    },
    {
      title: t('angularity.essay'),
      icon: AngularityIcon,
      key: 'angularity',
      standard: 'DNER - ME 415/2019',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit415_2019_me.pdf',
      type: 'aggregates',
    },
    {
      title: t('fatigue.essay'),
      icon: FatigueIcon,
      key: 'fatigue',
      standard: 'DNIT - ME 183/2018',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_183_2018_me-1.pdf',
      type: 'asphaltBinder',
    },
    {
      title: t('penetration.essay'),
      icon: PenetrationIcon,
      key: 'penetration',
      standard: 'DNIT - ME 155/2010',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_155_2010_me.pdf',
      type: 'asphaltBinder',
    },
    {
      title: t('marshall.essay'),
      icon: MarshallIconPng,
      key: 'marshall',
      standard: 'DNER - ME 043/95',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dner_me_043_95.pdf',
      type: 'asphaltMix',
    },
    {
      title: t('sand.equivalent'),
      icon: SandEquivalentIcon,
      key: 'sandEquivalent',
      standard: 'DNER - ME 054/97',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dner-me054-97.pdf',
      type: 'aggregates',
    },
    {
      title: t('storage.stability'),
      icon: StorageStabilityIcon,
      key: 'storageStability',
      standard: 'DNER - ME 384/99',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dner_me_384_99.pdf',
      type: 'asphaltBinder',
    },
    {
      title: t('drop.weight.deflectometer'),
      icon: FwdIcon,
      key: 'fallingWeightDeflectometer',
      standard: 'DNER-PRO 273/96',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/procedimento-pro/dner_pro_273_96.pdf',
      type: 'asphaltMix',
    },
    {
      title: t('flow.number'),
      icon: FlowNumberIcon,
      key: 'flowNumber',
      standard: 'DNIT 184/2018',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_184_2018_me-1.pdf',
      type: 'asphaltMix',
    },
    {
      title: t('multiple.stress.creep.recovery'),
      icon: MSCRIcon,
      key: 'mscr',
      standard: 'DNIT 423/2020 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_423_2020_me.pdf',
      type: 'asphaltMix',
    },
    {
      title: t('sieving.granulometry'),
      icon: GranulometryIcon,
      key: 'granulometry-asphalt',
      standard: 'DNER - ME 083/98',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dner-me083-98.pdf',
      type: 'aggregates',
    },
    {
      title: t('shape.index'),
      icon: ShapeIndexIcon,
      key: 'shapeIndex',
      standard: 'DNIT 424/2020 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_424_2020_me.pdf',
      type: 'aggregates',
    },
    {
      title: t('specific.mass-coarse.aggregate'),
      icon: SpecifyMassIcon,
      key: 'specifyMassBigAggregates',
      standard: 'DNIT 413/2021 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_413_2021_me.pdf',
      type: 'aggregates',
    },
    {
      title: t('specific.mass-fine.aggregate'),
      icon: SpecifyMassIcon,
      key: 'specifyMassSmallAggregates',
      standard: 'DNIT 411/2021 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_411_2021_me-1.pdf',
      type: 'aggregates',
    },
    {
      title: t('resilience.module'),
      icon: ResiliencyModuleIcon,
      key: 'resilienceModule',
      standard: 'DNIT 135/2018 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_135_2018_me-2.pdf',
      type: 'asphaltMix',
    },
    {
      title: t('elongated.flattened.particles'),
      icon: ElongatedParticlesIcon,
      key: 'elongatedParticles',
      standard: 'DNIT 429/2020 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_429_2020_me-3.pdf',
      type: 'aggregates',
    },
    {
      title: t('softening.point'),
      icon: SofteningPointIcon,
      key: 'softeningPoint',
      standard: 'DNIT 131/2010 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_131_2010_me.pdf',
      type: 'asphaltBinder',
    },
    {
      title: t('flash.point'),
      icon: FlashPointIcon,
      key: 'flashPoint',
      standard: 'DNER - ME 148/94',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dner_me_148_94.pdf',
      type: 'asphaltBinder',
    },
    {
      title: t('elastic.recovery'),
      icon: ElasticRecoveryIcon,
      key: 'elasticRecovery',
      standard: 'DNER 130/2010 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_130_2010_me.pdf',
      type: 'asphaltBinder',
    },
    {
      title: t('tensile.strength.by.diametral.compression-rt'),
      icon: RtcdIcon,
      key: 'rtcd',
      standard: 'DNIT 136/2018 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_136_2018_me-1.pdf',
      type: 'asphaltMix',
    },
    {
      title: t('rice.method'),
      icon: RiceTestIcon,
      key: 'rice',
      standard: 'DNIT 136/2018 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_136_2018_me-1.pdf',
      type: 'asphaltMix',
    },
    {
      title: t('rotational.viscosity'),
      icon: RotationalIcon,
      key: 'rotational',
      standard: 'DNIT 427/2020 - ME',
      link: 'https://www.gov.br/dnit/pt-br/assuntos/planejamento-e-pesquisa/ipr/coletanea-de-normas/coletanea-de-normas/metodo-de-ensaio-me/dnit_427_2020_me-2.pdf',
      type: 'asphaltBinder',
    },
  ];

  const filterOptions: FilterOption[] = [
    { key: 'all', title: t('all'), isSelected: true },
    { key: 'aggregates', title: t('aggregates'), isSelected: false },
    { key: 'asphaltMix', title: t('asphalt.mixtures'), isSelected: false },
    { key: 'asphaltBinder', title: t('asphalt.binder'), isSelected: false },
  ];

  return <StandardsTemplate standards={standards} filterOptions={filterOptions} />;
};

export default AsphaltStandards;
